spring:
    application:
      name: sm
    datasource:
      url: ${DB_URL_CONNECTION}
      driverClassName: ${DB_DRIVER_CLASS}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
    apininjas:
      url: ${API_APININJA_URL}
      token: ${API_APININJA_TOKEN}